runtime! debian.vim

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Disable Vi compatibility
set nocompatible

" Set line numbers
set number

" Always show cursor
set mouse=a
set ruler
set showcmd 

" Set command line height
set ch=1

" Disable line wrap
set nowrap

" Highlight pair brackets
set showmatch

" Allow to switch between buffers without saving
set hidden

" Search settings 
set incsearch
set hlsearch
set ignorecase
set smartcase

" Set default encoding
set termencoding=utf8

" Set default tab size
set shiftwidth=4
set tabstop=4
set softtabstop=4

" Use spaces instead of spaces
set expandtab
set encoding=utf-8
set smartindent
set showmatch
set autoindent

" Configure status bar
set statusline=%<%f%h%m%r\ %b\ %{&encoding}\ 0x\ \ %l,%c%V\ %P
set laststatus=2
set wildmenu

" Increase history size
set history=200

" Use Cyrillic symbols for navigation
set iskeyword=@,48-57,_,192-255

" Autocompletion on Tab
"function! SuperCleverTab()
"    if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
"        return "\<Tab>"
"    else
"        return "\<C-p>"
"    endif
"endfunction
"inoremap <Tab> <C-R>=SuperCleverTab()<cr>

set t_Co=256
set background=dark
colorscheme PaperColor

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

